apiVersion: v1
kind: Pod
metadata: 
  name: pvc-pod
spec:
  containers:
    - name: pvc-pod-container
      image: nginx
      volumeMounts: 
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: demo-pvc