apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy-app
  labels:
    app: my-deploy-app1
spec:
  strategy:
    #type: RollingUpdate   # rolling update strategy 
    #rollingUpdate:
    #  maxUnavailable: 1   #tells max no. of pods which remains unchanged
    type: Recreate
  replicas: 3
  selector:
    matchLabels: 
        app: my-deploy-app1
  template:
    metadata:
      name: my-deploy-pod
      labels:
        app: my-deploy-app1
    spec:
      containers:
        - name: nginx-port
          image: nginx:1.14.2
          ports:
            - containerPort: 80