apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod-app1
    env: devops
spec:
  containers:
    - name: podc1
      image: nginx
      ports:
         - name: nginx-port 
           containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: pod2-app
    env: devops
spec:
  containers:
    - name: pod2c1
      image: nginx
      ports:
        - name: nginx-port2
          containerPort: 80

    - name: pod2c2
      image: nginx
      ports:
       - name: nginx-port3
         containerPort: 80

