apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod-app1
    env: devops
spec:
containers:
  - name: podc1
    image: nginx
    ports:
    - name: nginx-port
      containerPort: 80
