apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: my-rc-app
spec:
  replicas: 3
  selector:
    app: my-app3
  template:
    metadata:
      name: rc-app
      labels:
        app: my-app3
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: nginx-port
              containerPort: 80
    
