apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-app
  labels:
    app: my-rset-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app4
    matchExpressions:
      - {key: app, operator: In, values: [my-app4]}  
  template:
    metadata:
      name: my-rset-app
      labels:
        app: my-app4
        env: devops
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: nginx-port
              containerPort: 80