apiVersion: v1
kind: Service
metadata:
  name: pod2-app-svc
spec: 
  type: LoadBalancer
  selector:
    app: pod2-app
  ports:
    - name: httpd
      protocol: TCP
      port: 80
      targetPort: 80
